### ISSUE TITLE
Angular CLI (Webpack 5) Error: Should not import the named export 'version'

### ISSUE THREAD

**Issue by sagewall** [jgravois/esri-leaflet-related#21]
I'm seeing the following error after upgrading to Angular 12:

./node_modules/esri-leaflet-related/node_modules/esri-leaflet/src/EsriLeaflet.js:2:0-51 - Error: Should not import the named export 'version' (reexported as 'VERSION') from default-exporting module (only default export is available soon)

This seems to be the result of using an older version of esri-leaflet as a dependency in esri-leaflet-related (^2.0.0-beta.4).  esri-leaflet@3.0.2 has fixed this issue (https://github.com/Esri/esri-leaflet/issues/1249) with pull request: https://github.com/Esri/esri-leaflet/pull/1273.  Would it be possible to update the esri-leaflet version used here in this repository to ^3.0.2?

**Comment by jgravois** [comment]
if can open a pull request to update to `^3.0.0`, i'd be happy to land it and release it as a breaking change.

**Comment by sagewall** [comment]
Thanks @jgravois I created [this pull request](https://github.com/jgravois/esri-leaflet-related/pull/22) to update esr-leaflet to ^3.0.0
